"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { History, X, Trash2, ChevronRight, LogIn, LogOut } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatDistanceToNow } from "date-fns";
import { useAuth } from "@/components/AuthProvider";
import { db } from "@/lib/firebase";
import { collection, query, orderBy, onSnapshot, addDoc, deleteDoc, doc, setDoc } from "firebase/firestore";

export interface HistoryItem {
    id: string;
    timestamp: number;
    mode: "roast" | "narrate";
    code: string;
    result: any; // TastingNote or PRDescription
    persona?: string;
    title?: string;
}

interface HistorySidebarProps {
    onSelect: (item: HistoryItem) => void;
    gameMode: "roast" | "narrate";
    newItem?: HistoryItem; // To trigger save
}

export function HistorySidebar({ onSelect, gameMode, newItem }: HistorySidebarProps) {
    const [isOpen, setIsOpen] = useState(false);
    const [history, setHistory] = useState<HistoryItem[]>([]);
    const { user, signInWithGoogle, logout } = useAuth();

    // Load history (Firestore if logged in, LocalStorage if guest)
    useEffect(() => {
        if (user) {
            // Subscribe to Firestore
            const q = query(
                collection(db, "users", user.uid, "history"),
                orderBy("timestamp", "desc")
            );
            const unsubscribe = onSnapshot(q, (snapshot) => {
                const items = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as HistoryItem));
                setHistory(items);
            });
            return () => unsubscribe();
        } else {
            // Load from LocalStorage
            const saved = localStorage.getItem("toprev-history");
            if (saved) {
                try {
                    setHistory(JSON.parse(saved));
                } catch (e) {
                    console.error("Failed to parse history", e);
                }
            }
        }
    }, [user]);

    // Save new item
    useEffect(() => {
        if (newItem) {
            if (user) {
                // Save to Firestore
                // We use setDoc with newItem.id to try to keep ID consistent or let firestore gen ID? 
                // newItem has an ID generated by crypto.randomUUID(). Let's use that as doc ID.
                setDoc(doc(db, "users", user.uid, "history", newItem.id), newItem);
            } else {
                // Save to LocalStorage
                setHistory(prev => {
                    // Check if already exists to avoid dupes (react strict mode double invoke)
                    if (prev.find(i => i.id === newItem.id)) return prev;

                    const updated = [newItem, ...prev].slice(0, 50);
                    localStorage.setItem("toprev-history", JSON.stringify(updated));
                    return updated;
                });
            }
        }
    }, [newItem, user]);

    const handleDelete = async (e: React.MouseEvent, id: string) => {
        e.stopPropagation();
        if (user) {
            await deleteDoc(doc(db, "users", user.uid, "history", id));
        } else {
            setHistory(prev => {
                const updated = prev.filter(item => item.id !== id);
                localStorage.setItem("toprev-history", JSON.stringify(updated));
                return updated;
            });
        }
    };

    const getModeIcon = (mode: string) => {
        return mode === "roast" ? "🔥" : "⚡";
    };

    return (
        <>
            <Button
                variant="ghost"
                size="icon"
                className="fixed top-4 left-4 z-50 text-zinc-500 hover:text-zinc-300 bg-zinc-950/50 backdrop-blur-sm border border-zinc-800"
                onClick={() => setIsOpen(true)}
            >
                <History className="w-5 h-5" />
            </Button>

            <AnimatePresence>
                {isOpen && (
                    <>
                        <motion.div
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 0.5 }}
                            exit={{ opacity: 0 }}
                            onClick={() => setIsOpen(false)}
                            className="fixed inset-0 bg-black/80 z-50 backdrop-blur-sm"
                        />
                        <motion.div
                            initial={{ x: -320 }}
                            animate={{ x: 0 }}
                            exit={{ x: -320 }}
                            transition={{ type: "spring", damping: 20 }}
                            className="fixed top-0 left-0 h-full w-80 bg-zinc-950 border-r border-zinc-800 z-50 flex flex-col shadow-2xl"
                        >
                            <div className="p-4 border-b border-zinc-800 flex items-center justify-between">
                                <h2 className="font-mono text-sm font-semibold text-zinc-400 flex items-center gap-2">
                                    <History className="w-4 h-4" /> History
                                </h2>
                                <Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => setIsOpen(false)}>
                                    <X className="w-4 h-4 text-zinc-500" />
                                </Button>
                            </div>

                            <div className="flex-1 overflow-y-auto p-2 space-y-2">
                                {history.length === 0 ? (
                                    <div className="text-center py-8 text-zinc-600 text-xs font-mono">
                                        No history yet.
                                        <br />
                                        Roast something!
                                    </div>
                                ) : (
                                    history.map((item) => (
                                        <div
                                            key={item.id}
                                            onClick={() => {
                                                onSelect(item);
                                                setIsOpen(false);
                                            }}
                                            className="group relative flex flex-col gap-1 p-3 rounded-md hover:bg-zinc-900 border border-transparent hover:border-zinc-800 cursor-pointer transition-all"
                                        >
                                            <div className="flex items-center justify-between">
                                                <span className="text-xs font-mono text-zinc-500 flex items-center gap-1">
                                                    {getModeIcon(item.mode)} {formatDistanceToNow(item.timestamp, { addSuffix: true })}
                                                </span>
                                                <Button
                                                    variant="ghost"
                                                    size="icon"
                                                    className="h-6 w-6 opacity-0 group-hover:opacity-100 transition-opacity text-zinc-600 hover:text-red-400"
                                                    onClick={(e) => handleDelete(e, item.id)}
                                                >
                                                    <Trash2 className="w-3 h-3" />
                                                </Button>
                                            </div>
                                            <p className="font-semibold text-sm text-zinc-300 truncate font-mono">
                                                {item.title || "Untitled Roast"}
                                            </p>
                                            {item.persona && (
                                                <span className="text-[10px] bg-zinc-800 text-zinc-400 px-1.5 py-0.5 rounded w-fit capitalize">
                                                    {item.persona}
                                                </span>
                                            )}
                                        </div>
                                    ))
                                )}
                            </div>

                            <div className="p-4 border-t border-zinc-800">
                                {user ? (
                                    <div className="flex flex-col gap-2">
                                        <div className="flex items-center gap-2">
                                            <div className="w-8 h-8 rounded-full bg-amber-500/20 text-amber-500 flex items-center justify-center font-bold text-xs border border-amber-500/50">
                                                {user.displayName?.charAt(0) || user.email?.charAt(0)}
                                            </div>
                                            <div className="flex-1 overflow-hidden">
                                                <p className="text-xs font-semibold text-zinc-300 truncate">{user.displayName}</p>
                                                <p className="text-[10px] text-zinc-500 truncate">{user.email}</p>
                                            </div>
                                        </div>
                                        <Button
                                            variant="outline"
                                            size="sm"
                                            className="w-full text-xs gap-2 border-zinc-800 bg-zinc-900/50 hover:bg-zinc-800 hover:text-red-400"
                                            onClick={logout}
                                        >
                                            <LogOut className="w-3 h-3" /> Sign Out
                                        </Button>
                                    </div>
                                ) : (
                                    <Button
                                        variant="default"
                                        size="sm"
                                        className="w-full text-xs gap-2 bg-indigo-600 hover:bg-indigo-700"
                                        onClick={signInWithGoogle}
                                    >
                                        <LogIn className="w-3 h-3" /> Sign In to Sync
                                    </Button>
                                )}
                            </div>
                        </motion.div>
                    </>
                )}
            </AnimatePresence>
        </>
    );
}
